name: Build LaTeX document
on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        continue-on-error: true
        with:
          root_file: main.tex
          texlive_version: 2024
          args: -f -xelatex -synctex=1 -file-line-error -interaction=nonstopmode
          extra_fonts: |
            ./Fonts/*.ttf
            ./Fonts/*.ttc
      - name: Upload PDF file
        uses: actions/upload-artifact@v4
        with:
          name: PDF
          path: main.pdf
      - name: Release PDF File
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: main.pdf
